
INSERT INTO public.platform_knowledge (category, title, content, keywords, priority, is_active) VALUES
('general', 'What is Shazam Parking', 'Shazam Parking is Dubai''s trusted monthly parking marketplace. We connect drivers who need a guaranteed long-term parking spot with owners who have a spare bay in their building. Everything is handled in one place: searching, booking, secure payments, owner payouts, identity checks and 24/7 chat support. We focus on monthly bookings (not pay-per-hour) so prices are predictable and spots are reserved exclusively for the driver during their booked period. Shazam Parking is part of the Shazam ecosystem alongside Dubai Life OS and Dubai Life Maps.', ARRAY['what is','about','shazam','platform','company','who are you','what do you do'], 100, true),

('general', 'How the platform works (drivers)', 'For drivers: 1) Search by zone or location on /find-a-parking-space. 2) Pick a spot and the start date — bookings are monthly. 3) Submit a booking request and complete the secure payment (manual capture, so you''re not charged until the owner confirms). 4) Once approved, the spot is yours for the booked period and you receive an email confirmation with full access details. 5) Need an access card? It''s a 500 AED refundable deposit + 100 AED handling fee, returned when you give the card back at the end.', ARRAY['how it works','driver','renter','book','find parking','how to book','process'], 95, true),

('general', 'How the platform works (owners)', 'For owners: 1) Click List on the bottom nav or go to /rent-out-your-space. 2) Add photos, location, monthly price and the rules. 3) Our team reviews and approves your listing within 24h. 4) When a driver books, you confirm or reject in your account. 5) Payouts are sent to your bank monthly after the booking starts — add your banking details in My Account to get paid. We handle all customer support, payments and disputes for you.', ARRAY['owner','landlord','list space','rent out','payout','how to list'], 95, true),

('general', 'Service zones in Dubai (full)', 'We currently cover: Dubai Marina, Downtown Dubai, Business Bay, DIFC, Palm Jumeirah, Deira, JBR, JLT, Al Barsha and surrounding areas. Each zone has its own dedicated landing page with available spots. New zones are added regularly — if you don''t see your area, contact support and we''ll let you know when it goes live.', ARRAY['zones','areas','where','locations','dubai','marina','downtown','difc','deira','palm'], 70, true),

('payment', 'Pricing model (monthly only)', 'All bookings on Shazam Parking are MONTHLY — we do not offer pay-per-hour. The price shown on each listing is the monthly rate in AED. Longer bookings (3, 6, 12 months) often have discounted rates set by the owner. The total you pay covers the full reserved period and the spot is exclusively yours during that time.', ARRAY['price','pricing','monthly','rate','cost','how much','per hour'], 90, true),

('payment', 'Payment flow (pre-authorisation)', 'When you book, your card is pre-authorised (held, not charged). The actual charge only happens when the owner confirms the booking — usually within 24 hours. If the owner rejects or doesn''t respond in time, the hold is released automatically and you''re not charged. All payments go through Stripe with full encryption.', ARRAY['payment','pay','charge','card','stripe','pre-authorisation','hold'], 85, true),

('booking', 'Booking timeline & advance notice', 'Bookings must start at least 24 hours in advance to give the owner time to confirm and prepare access. You''ll get email updates at every stage: request received → owner confirmed → payment captured → booking active. The exact same day-of-month start is recommended for clean monthly billing.', ARRAY['when','start','advance','24 hours','timeline','schedule'], 80, true),

('booking', 'Cancellation & refund (firm)', 'Once a booking is paid and confirmed, it is FINAL and non-refundable. This protects owners who reserve their spot exclusively for you. If you have a genuine dispute (e.g. spot not as described, access not provided), contact support immediately and we''ll investigate case-by-case.', ARRAY['cancel','refund','money back','non-refundable','dispute'], 90, true),

('account', 'Account types', 'There are two account types: "Driver" (find and book parking) and "Owner" (list spaces and earn). You can have both — toggle in My Account. Your phone number is mandatory for both account types so we can reach you about your bookings.', ARRAY['account','driver','owner','type','register','sign up'], 65, true),

('account', 'Identity verification (full)', 'KYC is required before your first booking can be confirmed (drivers) or your first listing goes live (owners). Upload Emirates ID or passport in My Account → Verification. Approval typically takes a few hours during business hours. Your documents are encrypted and only seen by our admin team.', ARRAY['kyc','verification','id','emirates','passport','verify'], 70, true),

('account', 'Banking details for payouts', 'Owners must add IBAN + bank name in My Account → Banking before receiving payouts. We pay out monthly in AED after each booked period starts. Without banking details, payouts are held until you add them.', ARRAY['banking','iban','bank','payout','salary','money'], 60, true),

('general', 'Live chat & human handoff', 'You''re chatting with Online Support — an AI assistant trained on every Shazam Parking policy and your own account data (bookings, listings, payouts). For anything sensitive (refunds, account issues, complaints, legal) I''ll instantly hand you over to a human teammate who will email you. You can also email support@shazamparking.ae directly or call the number on the Contact page.', ARRAY['human','agent','person','support','email','contact','help'], 80, true)
ON CONFLICT DO NOTHING;
